# Safety Security and License Configuration file

security:
    # A severity number between 0 and 10. Some helpful reference points:
    # - 9=ignore all vulnerabilities except CRITICAL severity.
    # - 7=ignore all vulnerabilities except CRITICAL & HIGH severity.
    # - 4=ignore all vulnerabilities except CRITICAL, HIGH & MEDIUM severity.
    ignore-cvss-severity-below: 0
    ignore-cvss-unknown-severity: False  # True or False. We recommend you set this to False.

    # Suppress non-zero exit codes when vulnerabilities are found.
    # Enable this in pipelines and CI/CD processes if you want to pass builds that have vulnerabilities.
    # We recommend you set this to False.
    continue-on-vulnerability-error: False

    # Here you can list multiple specific vulnerabilities you want to ignore/exempt (optionally for a time period)
    # We recommend making use of the optional `reason` and `expires` keys for each vulnerability that you ignore.
    ignore-vulnerabilities:
        51832:  # https://pyup.io/v/51832/97c
            reason: We won't be using GRIB2, see MAGIC/ops-data-store#29 for details
            expires: '2024-04-04'
        48545:  # https://pyup.io/v/48545/97c
            reason: it's unclear whether we're vulnerable to this, see MAGIC/ops-data-store#29 for details
            expires: '2024-04-04'
        61893:  # https://data.safetycli.com/v/61893/97c/
            reason: we're unable to use a newer version of Urllib3 see MAGIC/ops-data-store#127 for details
            expires: '2024-04-04'
        62044:  # https://data.safetycli.com/v/62044/f17
            reason: We are already using the latest version of pip currently available, risk score is very low
            expires: '2024-05-25'

# [Configuration for the `safety alert` command omitted as not used]
